### ISSUE TITLE
使用musl打包

### ISSUE THREAD

**Issue by xiao-zl** [fishandsheep/springnative#1]
使用musl打包报错 可以将 [musl](https://more.musl.cc/10.2.1/x86_64-linux-musl/x86_64-linux-musl-native.tgz)加到path中，我这运行正常，来着[这个](https://github.com/oracle/graal/issues/4076#issuecomment-1003161086)

**Comment by fishandsheep** [comment]
> 使用musl打包报错 可以将 [musl](https://more.musl.cc/10.2.1/x86_64-linux-musl/x86_64-linux-musl-native.tgz)加到path中，我这运行正常，来着[这个](https://github.com/oracle/graal/issues/4076#issuecomment-1003161086)

确实，是版本问题，感谢。
